-- A lot of mock data generated by ai












-- ============================================================
-- THEFACEBOOK 2004 CLONE
-- seed.sql
-- Development / fake data only
-- ============================================================

BEGIN;


-- ============================================================
-- 1. UNIVERSITIES
-- ============================================================

INSERT INTO universities (name, email_domain)
VALUES
    ('Harvard University', 'harvard.edu'),
    ('Yale University', 'yale.edu'),
    ('Massachusetts Institute of Technology', 'mit.edu'),
    ('Columbia University', 'columbia.edu'),
    ('Stanford University', 'stanford.edu')
ON CONFLICT DO NOTHING;


-- ============================================================
-- 2. USERS
-- ============================================================
-- password_hash values are DEVELOPMENT PLACEHOLDERS.
-- When authentication is implemented, generate real hashes
-- using the same hashing library as your FastAPI backend.
-- ============================================================

INSERT INTO users (
    university_id,
    first_name,
    last_name,
    email,
    password_hash
)
SELECT
    u.id,
    data.first_name,
    data.last_name,
    data.email,
    data.password_hash
FROM (
    VALUES
        (
            'Harvard University',
            'Alex',
            'Carter',
            'alex.carter@harvard.edu',
            'DEV_ONLY_HASH'
        ),
        (
            'Harvard University',
            'Emily',
            'Bennett',
            'emily.bennett@harvard.edu',
            'DEV_ONLY_HASH'
        ),
        (
            'Harvard University',
            'Daniel',
            'Brooks',
            'daniel.brooks@harvard.edu',
            'DEV_ONLY_HASH'
        ),
        (
            'Harvard University',
            'Sophia',
            'Mitchell',
            'sophia.mitchell@harvard.edu',
            'DEV_ONLY_HASH'
        ),
        (
            'Harvard University',
            'Ryan',
            'Foster',
            'ryan.foster@harvard.edu',
            'DEV_ONLY_HASH'
        ),
        (
            'Harvard University',
            'Olivia',
            'Reed',
            'olivia.reed@harvard.edu',
            'DEV_ONLY_HASH'
        ),
        (
            'Yale University',
            'Ethan',
            'Morgan',
            'ethan.morgan@yale.edu',
            'DEV_ONLY_HASH'
        ),
        (
            'Yale University',
            'Grace',
            'Turner',
            'grace.turner@yale.edu',
            'DEV_ONLY_HASH'
        ),
        (
            'Massachusetts Institute of Technology',
            'Noah',
            'Kim',
            'noah.kim@mit.edu',
            'DEV_ONLY_HASH'
        ),
        (
            'Massachusetts Institute of Technology',
            'Maya',
            'Patel',
            'maya.patel@mit.edu',
            'DEV_ONLY_HASH'
        ),
        (
            'Columbia University',
            'Lucas',
            'Rivera',
            'lucas.rivera@columbia.edu',
            'DEV_ONLY_HASH'
        ),
        (
            'Columbia University',
            'Ava',
            'Thompson',
            'ava.thompson@columbia.edu',
            'DEV_ONLY_HASH'
        ),
        (
            'Stanford University',
            'James',
            'Chen',
            'james.chen@stanford.edu',
            'DEV_ONLY_HASH'
        ),
        (
            'Stanford University',
            'Isabella',
            'Martinez',
            'isabella.martinez@stanford.edu',
            'DEV_ONLY_HASH'
        )
) AS data(
    university_name,
    first_name,
    last_name,
    email,
    password_hash
)
JOIN universities u
    ON u.name = data.university_name
ON CONFLICT DO NOTHING;


-- ============================================================
-- 3. PROFILES
-- ============================================================
-- We look users up by email rather than assuming IDs like
-- user_id = 1, 2, 3...
--
-- This is safer because identity sequences may already have
-- been used in your development database.
-- ============================================================

INSERT INTO profile (
    user_id,
    profile_pic,
    gender,
    status,
    residence,
    birth_date,
    home_town,
    high_school,
    username,
    mobile,
    websites,
    looking_for
)
SELECT
    u.id,
    data.profile_pic,
    data.gender,
    data.status,
    data.residence,
    data.birth_date::DATE,
    data.home_town,
    data.high_school,
    data.username,
    data.mobile,
    data.websites::JSONB,
    data.looking_for
FROM (
    VALUES

    (
        'alex.carter@harvard.edu',
        '/static/images/alex.jpg',
        'Male',
        'Student',
        'Kirkland House',
        '1985-02-14',
        'Boston, Massachusetts',
        'Boston Latin School',
        'acarter',
        '617-555-0101',
        '["https://example.com/alex"]',
        'Friendship, Networking'
    ),

    (
        'emily.bennett@harvard.edu',
        '/static/images/emily.jpg',
        'Female',
        'Student',
        'Eliot House',
        '1985-07-22',
        'New York, New York',
        'Stuyvesant High School',
        'ebennett',
        '617-555-0102',
        '["https://example.com/emily"]',
        'Friendship'
    ),

    (
        'daniel.brooks@harvard.edu',
        '/static/images/daniel.jpg',
        'Male',
        'Student',
        'Lowell House',
        '1984-11-05',
        'Chicago, Illinois',
        'Lincoln Park High School',
        'dbrooks',
        '617-555-0103',
        '[]',
        'Friendship, Dating'
    ),

    (
        'sophia.mitchell@harvard.edu',
        '/static/images/sophia.jpg',
        'Female',
        'Student',
        'Quincy House',
        '1985-04-12',
        'Seattle, Washington',
        'Garfield High School',
        'smitchell',
        '617-555-0104',
        '["https://example.com/sophia"]',
        'Friendship'
    ),

    (
        'ryan.foster@harvard.edu',
        '/static/images/ryan.jpg',
        'Male',
        'Student',
        'Winthrop House',
        '1984-09-17',
        'Austin, Texas',
        'Westlake High School',
        'rfoster',
        '617-555-0105',
        '[]',
        'Networking'
    ),

    (
        'olivia.reed@harvard.edu',
        '/static/images/olivia.jpg',
        'Female',
        'Student',
        'Adams House',
        '1985-01-30',
        'Portland, Oregon',
        'Lincoln High School',
        'oreed',
        '617-555-0106',
        '[]',
        'Friendship'
    ),

    (
        'ethan.morgan@yale.edu',
        '/static/images/ethan.jpg',
        'Male',
        'Student',
        'New Haven, Connecticut',
        '1985-05-06',
        'Philadelphia, Pennsylvania',
        'Central High School',
        'emorgan',
        '203-555-0101',
        '[]',
        'Networking'
    ),

    (
        'grace.turner@yale.edu',
        '/static/images/grace.jpg',
        'Female',
        'Student',
        'New Haven, Connecticut',
        '1985-03-18',
        'Providence, Rhode Island',
        'Classical High School',
        'gturner',
        '203-555-0102',
        '[]',
        'Friendship'
    ),

    (
        'noah.kim@mit.edu',
        '/static/images/noah.jpg',
        'Male',
        'Student',
        'Cambridge, Massachusetts',
        '1985-08-03',
        'San Jose, California',
        'Lynbrook High School',
        'nkim',
        '617-555-0201',
        '["https://example.com/noah"]',
        'Networking'
    ),

    (
        'maya.patel@mit.edu',
        '/static/images/maya.jpg',
        'Female',
        'Student',
        'Cambridge, Massachusetts',
        '1985-12-11',
        'Edison, New Jersey',
        'Edison High School',
        'mpatel',
        '617-555-0202',
        '[]',
        'Friendship, Networking'
    ),

    (
        'lucas.rivera@columbia.edu',
        '/static/images/lucas.jpg',
        'Male',
        'Student',
        'New York, New York',
        '1984-06-21',
        'Miami, Florida',
        'Coral Gables High School',
        'lrivera',
        '212-555-0101',
        '[]',
        'Friendship'
    ),

    (
        'ava.thompson@columbia.edu',
        '/static/images/ava.jpg',
        'Female',
        'Student',
        'New York, New York',
        '1985-10-09',
        'Brooklyn, New York',
        'Brooklyn Technical High School',
        'athompson',
        '212-555-0102',
        '[]',
        'Networking'
    ),

    (
        'james.chen@stanford.edu',
        '/static/images/james.jpg',
        'Male',
        'Student',
        'Palo Alto, California',
        '1984-03-27',
        'San Francisco, California',
        'Lowell High School',
        'jchen',
        '650-555-0101',
        '["https://example.com/james"]',
        'Networking'
    ),

    (
        'isabella.martinez@stanford.edu',
        '/static/images/isabella.jpg',
        'Female',
        'Student',
        'Palo Alto, California',
        '1985-06-15',
        'Los Angeles, California',
        'Fairfax High School',
        'imartinez',
        '650-555-0102',
        '[]',
        'Friendship'
    )

) AS data(
    email,
    profile_pic,
    gender,
    status,
    residence,
    birth_date,
    home_town,
    high_school,
    username,
    mobile,
    websites,
    looking_for
)

JOIN users u
    ON LOWER(u.email) = LOWER(data.email)

ON CONFLICT DO NOTHING;


-- ============================================================
-- 4. COURSES
-- ============================================================

INSERT INTO courses (
    university_id,
    course_code,
    course_name,
    academic_year,
    semester
)
SELECT
    u.id,
    data.course_code,
    data.course_name,
    data.academic_year,
    data.semester
FROM (
    VALUES

        (
            'Harvard University',
            'CS50',
            'Introduction to Computer Science',
            2004::SMALLINT,
            'Fall'
        ),

        (
            'Harvard University',
            'ECON10',
            'Principles of Economics',
            2004::SMALLINT,
            'Fall'
        ),

        (
            'Harvard University',
            'MATH21A',
            'Multivariable Calculus',
            2004::SMALLINT,
            'Fall'
        ),

        (
            'Harvard University',
            'GOV20',
            'Foundations of Comparative Politics',
            2004::SMALLINT,
            'Fall'
        ),

        (
            'Yale University',
            'CPSC201',
            'Introduction to Computer Science',
            2004::SMALLINT,
            'Fall'
        ),

        (
            'Yale University',
            'ECON115',
            'Introductory Microeconomics',
            2004::SMALLINT,
            'Fall'
        ),

        (
            'Massachusetts Institute of Technology',
            '6.001',
            'Structure and Interpretation of Computer Programs',
            2004::SMALLINT,
            'Fall'
        ),

        (
            'Massachusetts Institute of Technology',
            '18.01',
            'Single Variable Calculus',
            2004::SMALLINT,
            'Fall'
        ),

        (
            'Columbia University',
            'COMS1004',
            'Introduction to Computer Science',
            2004::SMALLINT,
            'Fall'
        ),

        (
            'Stanford University',
            'CS106A',
            'Programming Methodology',
            2004::SMALLINT,
            'Fall'
        )

) AS data(
    university_name,
    course_code,
    course_name,
    academic_year,
    semester
)

JOIN universities u
    ON u.name = data.university_name

ON CONFLICT DO NOTHING;


-- ============================================================
-- 5. FRIENDSHIPS
-- ============================================================
--
-- Your friendship table requires:
--
-- user_id_low < user_id_high
--
-- So LEAST() and GREATEST() guarantee canonical ordering.
-- ============================================================

INSERT INTO friendships (
    user_id_low,
    user_id_high,
    requested_by,
    status,
    responded_at
)
SELECT
    LEAST(u1.id, u2.id),
    GREATEST(u1.id, u2.id),
    requester.id,
    data.status,
    CASE
        WHEN data.status = 'accepted' THEN NOW()
        WHEN data.status = 'rejected' THEN NOW()
        ELSE NULL
    END
FROM (
    VALUES

        (
            'alex.carter@harvard.edu',
            'emily.bennett@harvard.edu',
            'alex.carter@harvard.edu',
            'accepted'
        ),

        (
            'alex.carter@harvard.edu',
            'daniel.brooks@harvard.edu',
            'daniel.brooks@harvard.edu',
            'accepted'
        ),

        (
            'alex.carter@harvard.edu',
            'sophia.mitchell@harvard.edu',
            'alex.carter@harvard.edu',
            'accepted'
        ),

        (
            'alex.carter@harvard.edu',
            'ryan.foster@harvard.edu',
            'ryan.foster@harvard.edu',
            'pending'
        ),

        (
            'alex.carter@harvard.edu',
            'olivia.reed@harvard.edu',
            'olivia.reed@harvard.edu',
            'accepted'
        ),

        (
            'emily.bennett@harvard.edu',
            'sophia.mitchell@harvard.edu',
            'emily.bennett@harvard.edu',
            'accepted'
        ),

        (
            'emily.bennett@harvard.edu',
            'olivia.reed@harvard.edu',
            'olivia.reed@harvard.edu',
            'accepted'
        ),

        (
            'daniel.brooks@harvard.edu',
            'ryan.foster@harvard.edu',
            'daniel.brooks@harvard.edu',
            'accepted'
        ),

        (
            'daniel.brooks@harvard.edu',
            'sophia.mitchell@harvard.edu',
            'sophia.mitchell@harvard.edu',
            'pending'
        ),

        (
            'ryan.foster@harvard.edu',
            'olivia.reed@harvard.edu',
            'ryan.foster@harvard.edu',
            'accepted'
        ),

        (
            'ethan.morgan@yale.edu',
            'grace.turner@yale.edu',
            'ethan.morgan@yale.edu',
            'accepted'
        ),

        (
            'noah.kim@mit.edu',
            'maya.patel@mit.edu',
            'maya.patel@mit.edu',
            'accepted'
        ),

        (
            'lucas.rivera@columbia.edu',
            'ava.thompson@columbia.edu',
            'lucas.rivera@columbia.edu',
            'accepted'
        ),

        (
            'james.chen@stanford.edu',
            'isabella.martinez@stanford.edu',
            'james.chen@stanford.edu',
            'accepted'
        ),

        (
            'alex.carter@harvard.edu',
            'noah.kim@mit.edu',
            'alex.carter@harvard.edu',
            'pending'
        ),

        (
            'sophia.mitchell@harvard.edu',
            'grace.turner@yale.edu',
            'grace.turner@yale.edu',
            'accepted'
        ),

        (
            'maya.patel@mit.edu',
            'ava.thompson@columbia.edu',
            'maya.patel@mit.edu',
            'pending'
        ),

        (
            'daniel.brooks@harvard.edu',
            'lucas.rivera@columbia.edu',
            'lucas.rivera@columbia.edu',
            'rejected'
        )

) AS data(
    email_1,
    email_2,
    requester_email,
    status
)

JOIN users u1
    ON LOWER(u1.email) = LOWER(data.email_1)

JOIN users u2
    ON LOWER(u2.email) = LOWER(data.email_2)

JOIN users requester
    ON LOWER(requester.email) = LOWER(data.requester_email)

ON CONFLICT DO NOTHING;


-- ============================================================
-- 6. ENROLLMENTS
-- ============================================================

INSERT INTO enrollments (
    user_id,
    course_id
)
SELECT
    u.id,
    c.id
FROM (
    VALUES

        ('alex.carter@harvard.edu', 'CS50'),
        ('alex.carter@harvard.edu', 'ECON10'),

        ('emily.bennett@harvard.edu', 'CS50'),
        ('emily.bennett@harvard.edu', 'GOV20'),

        ('daniel.brooks@harvard.edu', 'ECON10'),
        ('daniel.brooks@harvard.edu', 'MATH21A'),

        ('sophia.mitchell@harvard.edu', 'CS50'),
        ('sophia.mitchell@harvard.edu', 'MATH21A'),

        ('ryan.foster@harvard.edu', 'CS50'),
        ('ryan.foster@harvard.edu', 'ECON10'),

        ('olivia.reed@harvard.edu', 'GOV20'),
        ('olivia.reed@harvard.edu', 'CS50'),

        ('ethan.morgan@yale.edu', 'CPSC201'),
        ('ethan.morgan@yale.edu', 'ECON115'),

        ('grace.turner@yale.edu', 'CPSC201'),

        ('noah.kim@mit.edu', '6.001'),
        ('noah.kim@mit.edu', '18.01'),

        ('maya.patel@mit.edu', '6.001'),

        ('lucas.rivera@columbia.edu', 'COMS1004'),

        ('ava.thompson@columbia.edu', 'COMS1004'),

        ('james.chen@stanford.edu', 'CS106A'),

        ('isabella.martinez@stanford.edu', 'CS106A')

) AS data(
    email,
    course_code
)

JOIN users u
    ON LOWER(u.email) = LOWER(data.email)

JOIN courses c
    ON c.course_code = data.course_code
    AND c.university_id = u.university_id
    AND c.academic_year = 2004
    AND LOWER(c.semester) = 'fall'

ON CONFLICT DO NOTHING;


COMMIT;


-- ============================================================
-- OPTIONAL CHECKS
-- ============================================================

SELECT COUNT(*) AS universities FROM universities;
SELECT COUNT(*) AS users FROM users;
SELECT COUNT(*) AS profiles FROM profile;
SELECT COUNT(*) AS friendships FROM friendships;
SELECT COUNT(*) AS courses FROM courses;
SELECT COUNT(*) AS enrollments FROM enrollments;